// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos_sample/app/device/internal/biz"
	"kratos_sample/app/device/internal/conf"
	"kratos_sample/app/device/internal/data"
	"kratos_sample/app/device/internal/server"
	"kratos_sample/app/device/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//	func wireApp(*conf.Server, *conf.Data, *conf.Registry, log.Logger) (*kratos.App, func(), error) {
//		panic(wire.Build(server.ProviderSet, data.ProviderSet, biz.ProviderSet, service.ProviderSet, newApp))
//	}
func wireApp(confServer *conf.Server, etcd *conf.Etcd, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar, cleanup, err := data.NewRegistrar(etcd, logger)
	if err != nil {
		return nil, nil, err
	}
	db := data.NewDB(confData)
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	deviceRepo := data.NewDeviceRepo(dataData, logger)
	deviceUsecase := biz.NewDeviceUsecase(deviceRepo, logger)
	deviceService := service.NewDeviceService(deviceUsecase)
	grpcServer := server.NewGRPCServer(confServer, deviceService, logger)
	app := newApp(registrar, logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
