// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: api/gateway/v1/gateway.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayRequest) Reset() {
	*x = CreateGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayRequest) ProtoMessage() {}

func (x *CreateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayRequest.ProtoReflect.Descriptor instead.
func (*CreateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type CreateGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayReply) Reset() {
	*x = CreateGatewayReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayReply) ProtoMessage() {}

func (x *CreateGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayReply.ProtoReflect.Descriptor instead.
func (*CreateGatewayReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

type UpdateGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGatewayRequest) Reset() {
	*x = UpdateGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGatewayRequest) ProtoMessage() {}

func (x *UpdateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGatewayRequest.ProtoReflect.Descriptor instead.
func (*UpdateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

type UpdateGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGatewayReply) Reset() {
	*x = UpdateGatewayReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGatewayReply) ProtoMessage() {}

func (x *UpdateGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGatewayReply.ProtoReflect.Descriptor instead.
func (*UpdateGatewayReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type DeleteGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGatewayRequest) Reset() {
	*x = DeleteGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGatewayRequest) ProtoMessage() {}

func (x *DeleteGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGatewayRequest.ProtoReflect.Descriptor instead.
func (*DeleteGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

type DeleteGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGatewayReply) Reset() {
	*x = DeleteGatewayReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGatewayReply) ProtoMessage() {}

func (x *DeleteGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGatewayReply.ProtoReflect.Descriptor instead.
func (*DeleteGatewayReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

type GetGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayRequest) Reset() {
	*x = GetGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayRequest) ProtoMessage() {}

func (x *GetGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

type GetGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayReply) Reset() {
	*x = GetGatewayReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayReply) ProtoMessage() {}

func (x *GetGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayReply.ProtoReflect.Descriptor instead.
func (*GetGatewayReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

type ListGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewayRequest) Reset() {
	*x = ListGatewayRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewayRequest) ProtoMessage() {}

func (x *ListGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewayRequest.ProtoReflect.Descriptor instead.
func (*ListGatewayRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

type ListGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewayReply) Reset() {
	*x = ListGatewayReply{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewayReply) ProtoMessage() {}

func (x *ListGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewayReply.ProtoReflect.Descriptor instead.
func (*ListGatewayReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

var File_api_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_api_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1capi/gateway/v1/gateway.proto\x12\x0eapi.gateway.v1\x1a\x1cgoogle/api/annotations.proto\"\x16\n" +
	"\x14CreateGatewayRequest\"\x14\n" +
	"\x12CreateGatewayReply\"\x16\n" +
	"\x14UpdateGatewayRequest\"\x14\n" +
	"\x12UpdateGatewayReply\"\x16\n" +
	"\x14DeleteGatewayRequest\"\x14\n" +
	"\x12DeleteGatewayReply\"\x13\n" +
	"\x11GetGatewayRequest\"\x11\n" +
	"\x0fGetGatewayReply\"\x14\n" +
	"\x12ListGatewayRequest\"\x12\n" +
	"\x10ListGatewayReply2\xda\x03\n" +
	"\aGateway\x12Y\n" +
	"\rCreateGateway\x12$.api.gateway.v1.CreateGatewayRequest\x1a\".api.gateway.v1.CreateGatewayReply\x12Y\n" +
	"\rUpdateGateway\x12$.api.gateway.v1.UpdateGatewayRequest\x1a\".api.gateway.v1.UpdateGatewayReply\x12Y\n" +
	"\rDeleteGateway\x12$.api.gateway.v1.DeleteGatewayRequest\x1a\".api.gateway.v1.DeleteGatewayReply\x12P\n" +
	"\n" +
	"GetGateway\x12!.api.gateway.v1.GetGatewayRequest\x1a\x1f.api.gateway.v1.GetGatewayReply\x12l\n" +
	"\vListGateway\x12\".api.gateway.v1.ListGatewayRequest\x1a .api.gateway.v1.ListGatewayReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/device/listB;\n" +
	"\x0eapi.gateway.v1P\x01Z'kratos_sample/api/gateway/service/v1;v1b\x06proto3"

var (
	file_api_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_api_gateway_v1_gateway_proto_rawDescData []byte
)

func file_api_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_api_gateway_v1_gateway_proto_rawDescData
}

var file_api_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gateway_v1_gateway_proto_goTypes = []any{
	(*CreateGatewayRequest)(nil), // 0: api.gateway.v1.CreateGatewayRequest
	(*CreateGatewayReply)(nil),   // 1: api.gateway.v1.CreateGatewayReply
	(*UpdateGatewayRequest)(nil), // 2: api.gateway.v1.UpdateGatewayRequest
	(*UpdateGatewayReply)(nil),   // 3: api.gateway.v1.UpdateGatewayReply
	(*DeleteGatewayRequest)(nil), // 4: api.gateway.v1.DeleteGatewayRequest
	(*DeleteGatewayReply)(nil),   // 5: api.gateway.v1.DeleteGatewayReply
	(*GetGatewayRequest)(nil),    // 6: api.gateway.v1.GetGatewayRequest
	(*GetGatewayReply)(nil),      // 7: api.gateway.v1.GetGatewayReply
	(*ListGatewayRequest)(nil),   // 8: api.gateway.v1.ListGatewayRequest
	(*ListGatewayReply)(nil),     // 9: api.gateway.v1.ListGatewayReply
}
var file_api_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // 0: api.gateway.v1.Gateway.CreateGateway:input_type -> api.gateway.v1.CreateGatewayRequest
	2, // 1: api.gateway.v1.Gateway.UpdateGateway:input_type -> api.gateway.v1.UpdateGatewayRequest
	4, // 2: api.gateway.v1.Gateway.DeleteGateway:input_type -> api.gateway.v1.DeleteGatewayRequest
	6, // 3: api.gateway.v1.Gateway.GetGateway:input_type -> api.gateway.v1.GetGatewayRequest
	8, // 4: api.gateway.v1.Gateway.ListGateway:input_type -> api.gateway.v1.ListGatewayRequest
	1, // 5: api.gateway.v1.Gateway.CreateGateway:output_type -> api.gateway.v1.CreateGatewayReply
	3, // 6: api.gateway.v1.Gateway.UpdateGateway:output_type -> api.gateway.v1.UpdateGatewayReply
	5, // 7: api.gateway.v1.Gateway.DeleteGateway:output_type -> api.gateway.v1.DeleteGatewayReply
	7, // 8: api.gateway.v1.Gateway.GetGateway:output_type -> api.gateway.v1.GetGatewayReply
	9, // 9: api.gateway.v1.Gateway.ListGateway:output_type -> api.gateway.v1.ListGatewayReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_gateway_proto_init() }
func file_api_gateway_v1_gateway_proto_init() {
	if File_api_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_gateway_proto = out.File
	file_api_gateway_v1_gateway_proto_goTypes = nil
	file_api_gateway_v1_gateway_proto_depIdxs = nil
}
