// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: api/device/v1/device.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_api_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *IDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListDeviceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Page              uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页索引
	PageSize          uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 页大小
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GroupId           int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PlayerFingerprint string                 `protobuf:"bytes,5,opt,name=player_fingerprint,json=playerFingerprint,proto3" json:"player_fingerprint,omitempty"` //播放器指纹
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListDeviceRequest) Reset() {
	*x = ListDeviceRequest{}
	mi := &file_api_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceRequest) ProtoMessage() {}

func (x *ListDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *ListDeviceRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeviceRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDeviceRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListDeviceRequest) GetPlayerFingerprint() string {
	if x != nil {
		return x.PlayerFingerprint
	}
	return ""
}

type ListDeviceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DeviceInfo          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceReply) Reset() {
	*x = ListDeviceReply{}
	mi := &file_api_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceReply) ProtoMessage() {}

func (x *ListDeviceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceReply.ProtoReflect.Descriptor instead.
func (*ListDeviceReply) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *ListDeviceReply) GetData() []*DeviceInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListDeviceReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeviceInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GroupId               int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DeviceId              string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Dnum                  int64                  `protobuf:"varint,5,opt,name=dnum,proto3" json:"dnum,omitempty"`
	Serial                string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	Projectid             uint32                 `protobuf:"varint,7,opt,name=projectid,proto3" json:"projectid,omitempty"`
	IotId                 string                 `protobuf:"bytes,8,opt,name=iot_id,json=iotId,proto3" json:"iot_id,omitempty"`
	CertId                string                 `protobuf:"bytes,9,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	Mac                   string                 `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	ClientType            string                 `protobuf:"bytes,12,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	SetShadow             uint32                 `protobuf:"varint,13,opt,name=set_shadow,json=setShadow,proto3" json:"set_shadow,omitempty"`
	Rotation              uint32                 `protobuf:"varint,14,opt,name=rotation,proto3" json:"rotation,omitempty"`
	SoftwareVersion       string                 `protobuf:"bytes,15,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AppVersion            string                 `protobuf:"bytes,16,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Brand                 string                 `protobuf:"bytes,17,opt,name=brand,proto3" json:"brand,omitempty"`
	Source                int32                  `protobuf:"varint,18,opt,name=source,proto3" json:"source,omitempty"`
	ModelId               uint64                 `protobuf:"varint,19,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName             string                 `protobuf:"bytes,20,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	HaveOss               int32                  `protobuf:"varint,21,opt,name=have_oss,json=haveOss,proto3" json:"have_oss,omitempty"`
	FrontendStyle         int32                  `protobuf:"varint,22,opt,name=frontend_style,json=frontendStyle,proto3" json:"frontend_style,omitempty"`
	Status                uint32                 `protobuf:"varint,23,opt,name=status,proto3" json:"status,omitempty"`
	ActiveBy              uint64                 `protobuf:"varint,24,opt,name=active_by,json=activeBy,proto3" json:"active_by,omitempty"`
	ActiveTime            int32                  `protobuf:"varint,25,opt,name=active_time,json=activeTime,proto3" json:"active_time,omitempty"`
	ConfirmBy             uint64                 `protobuf:"varint,26,opt,name=confirm_by,json=confirmBy,proto3" json:"confirm_by,omitempty"`
	UserGroupId           int64                  `protobuf:"varint,27,opt,name=user_group_id,json=userGroupId,proto3" json:"user_group_id,omitempty"`
	CreateTime            uint32                 `protobuf:"varint,28,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime            uint32                 `protobuf:"varint,29,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ScreenCaptureInterval int32                  `protobuf:"varint,31,opt,name=screen_capture_interval,json=screenCaptureInterval,proto3" json:"screen_capture_interval,omitempty"`
	AutoScreenCapture     int32                  `protobuf:"varint,32,opt,name=auto_screen_capture,json=autoScreenCapture,proto3" json:"auto_screen_capture,omitempty"`
	PlayerFingerprint     string                 `protobuf:"bytes,33,opt,name=player_fingerprint,json=playerFingerprint,proto3" json:"player_fingerprint,omitempty"`
	PlayerComponents      []byte                 `protobuf:"bytes,34,opt,name=player_components,json=playerComponents,proto3" json:"player_components,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDnum() int64 {
	if x != nil {
		return x.Dnum
	}
	return 0
}

func (x *DeviceInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceInfo) GetProjectid() uint32 {
	if x != nil {
		return x.Projectid
	}
	return 0
}

func (x *DeviceInfo) GetIotId() string {
	if x != nil {
		return x.IotId
	}
	return ""
}

func (x *DeviceInfo) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

func (x *DeviceInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DeviceInfo) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *DeviceInfo) GetSetShadow() uint32 {
	if x != nil {
		return x.SetShadow
	}
	return 0
}

func (x *DeviceInfo) GetRotation() uint32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *DeviceInfo) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceInfo) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *DeviceInfo) GetModelId() uint64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *DeviceInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *DeviceInfo) GetHaveOss() int32 {
	if x != nil {
		return x.HaveOss
	}
	return 0
}

func (x *DeviceInfo) GetFrontendStyle() int32 {
	if x != nil {
		return x.FrontendStyle
	}
	return 0
}

func (x *DeviceInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeviceInfo) GetActiveBy() uint64 {
	if x != nil {
		return x.ActiveBy
	}
	return 0
}

func (x *DeviceInfo) GetActiveTime() int32 {
	if x != nil {
		return x.ActiveTime
	}
	return 0
}

func (x *DeviceInfo) GetConfirmBy() uint64 {
	if x != nil {
		return x.ConfirmBy
	}
	return 0
}

func (x *DeviceInfo) GetUserGroupId() int64 {
	if x != nil {
		return x.UserGroupId
	}
	return 0
}

func (x *DeviceInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *DeviceInfo) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *DeviceInfo) GetScreenCaptureInterval() int32 {
	if x != nil {
		return x.ScreenCaptureInterval
	}
	return 0
}

func (x *DeviceInfo) GetAutoScreenCapture() int32 {
	if x != nil {
		return x.AutoScreenCapture
	}
	return 0
}

func (x *DeviceInfo) GetPlayerFingerprint() string {
	if x != nil {
		return x.PlayerFingerprint
	}
	return ""
}

func (x *DeviceInfo) GetPlayerComponents() []byte {
	if x != nil {
		return x.PlayerComponents
	}
	return nil
}

type DeviceGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lock          int32                  `protobuf:"varint,3,opt,name=lock,proto3" json:"lock,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceGroupInfo) Reset() {
	*x = DeviceGroupInfo{}
	mi := &file_api_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGroupInfo) ProtoMessage() {}

func (x *DeviceGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGroupInfo.ProtoReflect.Descriptor instead.
func (*DeviceGroupInfo) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceGroupInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DeviceGroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceGroupInfo) GetLock() int32 {
	if x != nil {
		return x.Lock
	}
	return 0
}

func (x *DeviceGroupInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeviceGroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DeviceGroupInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceGroupListResponse) Reset() {
	*x = DeviceGroupListResponse{}
	mi := &file_api_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGroupListResponse) ProtoMessage() {}

func (x *DeviceGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGroupListResponse.ProtoReflect.Descriptor instead.
func (*DeviceGroupListResponse) Descriptor() ([]byte, []int) {
	return file_api_device_v1_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceGroupListResponse) GetList() []*DeviceGroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_device_v1_device_proto protoreflect.FileDescriptor

const file_api_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/device/v1/device.proto\x12\rapi.device.v1\x1a\x1cgoogle/api/annotations.proto\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa2\x01\n" +
	"\x11ListDeviceRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12-\n" +
	"\x12player_fingerprint\x18\x05 \x01(\tR\x11playerFingerprint\"V\n" +
	"\x0fListDeviceReply\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.api.device.v1.DeviceInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe5\a\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04dnum\x18\x05 \x01(\x03R\x04dnum\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12\x1c\n" +
	"\tprojectid\x18\a \x01(\rR\tprojectid\x12\x15\n" +
	"\x06iot_id\x18\b \x01(\tR\x05iotId\x12\x17\n" +
	"\acert_id\x18\t \x01(\tR\x06certId\x12\x10\n" +
	"\x03mac\x18\n" +
	" \x01(\tR\x03mac\x12\x1f\n" +
	"\vclient_type\x18\f \x01(\tR\n" +
	"clientType\x12\x1d\n" +
	"\n" +
	"set_shadow\x18\r \x01(\rR\tsetShadow\x12\x1a\n" +
	"\brotation\x18\x0e \x01(\rR\brotation\x12)\n" +
	"\x10software_version\x18\x0f \x01(\tR\x0fsoftwareVersion\x12\x1f\n" +
	"\vapp_version\x18\x10 \x01(\tR\n" +
	"appVersion\x12\x14\n" +
	"\x05brand\x18\x11 \x01(\tR\x05brand\x12\x16\n" +
	"\x06source\x18\x12 \x01(\x05R\x06source\x12\x19\n" +
	"\bmodel_id\x18\x13 \x01(\x04R\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x14 \x01(\tR\tmodelName\x12\x19\n" +
	"\bhave_oss\x18\x15 \x01(\x05R\ahaveOss\x12%\n" +
	"\x0efrontend_style\x18\x16 \x01(\x05R\rfrontendStyle\x12\x16\n" +
	"\x06status\x18\x17 \x01(\rR\x06status\x12\x1b\n" +
	"\tactive_by\x18\x18 \x01(\x04R\bactiveBy\x12\x1f\n" +
	"\vactive_time\x18\x19 \x01(\x05R\n" +
	"activeTime\x12\x1d\n" +
	"\n" +
	"confirm_by\x18\x1a \x01(\x04R\tconfirmBy\x12\"\n" +
	"\ruser_group_id\x18\x1b \x01(\x03R\vuserGroupId\x12\x1f\n" +
	"\vcreate_time\x18\x1c \x01(\rR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x1d \x01(\rR\n" +
	"updateTime\x126\n" +
	"\x17screen_capture_interval\x18\x1f \x01(\x05R\x15screenCaptureInterval\x12.\n" +
	"\x13auto_screen_capture\x18  \x01(\x05R\x11autoScreenCapture\x12-\n" +
	"\x12player_fingerprint\x18! \x01(\tR\x11playerFingerprint\x12+\n" +
	"\x11player_components\x18\" \x01(\fR\x10playerComponents\"j\n" +
	"\x0fDeviceGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04lock\x18\x03 \x01(\x05R\x04lock\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"M\n" +
	"\x17DeviceGroupListResponse\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.api.device.v1.DeviceGroupInfoR\x04list2\xb0\x01\n" +
	"\x06Device\x12N\n" +
	"\n" +
	"ListDevice\x12 .api.device.v1.ListDeviceRequest\x1a\x1e.api.device.v1.ListDeviceReply\x12V\n" +
	"\x12DeviceGroupAllList\x12\x18.api.device.v1.IDRequest\x1a&.api.device.v1.DeviceGroupListResponseB1\n" +
	"\rapi.device.v1P\x01Z\x1ekratos_sample/api/device/v1;v1b\x06proto3"

var (
	file_api_device_v1_device_proto_rawDescOnce sync.Once
	file_api_device_v1_device_proto_rawDescData []byte
)

func file_api_device_v1_device_proto_rawDescGZIP() []byte {
	file_api_device_v1_device_proto_rawDescOnce.Do(func() {
		file_api_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_device_v1_device_proto_rawDesc), len(file_api_device_v1_device_proto_rawDesc)))
	})
	return file_api_device_v1_device_proto_rawDescData
}

var file_api_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_device_v1_device_proto_goTypes = []any{
	(*IDRequest)(nil),               // 0: api.device.v1.IDRequest
	(*ListDeviceRequest)(nil),       // 1: api.device.v1.ListDeviceRequest
	(*ListDeviceReply)(nil),         // 2: api.device.v1.ListDeviceReply
	(*DeviceInfo)(nil),              // 3: api.device.v1.DeviceInfo
	(*DeviceGroupInfo)(nil),         // 4: api.device.v1.DeviceGroupInfo
	(*DeviceGroupListResponse)(nil), // 5: api.device.v1.DeviceGroupListResponse
}
var file_api_device_v1_device_proto_depIdxs = []int32{
	3, // 0: api.device.v1.ListDeviceReply.data:type_name -> api.device.v1.DeviceInfo
	4, // 1: api.device.v1.DeviceGroupListResponse.list:type_name -> api.device.v1.DeviceGroupInfo
	1, // 2: api.device.v1.Device.ListDevice:input_type -> api.device.v1.ListDeviceRequest
	0, // 3: api.device.v1.Device.DeviceGroupAllList:input_type -> api.device.v1.IDRequest
	2, // 4: api.device.v1.Device.ListDevice:output_type -> api.device.v1.ListDeviceReply
	5, // 5: api.device.v1.Device.DeviceGroupAllList:output_type -> api.device.v1.DeviceGroupListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_device_v1_device_proto_init() }
func file_api_device_v1_device_proto_init() {
	if File_api_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_device_v1_device_proto_rawDesc), len(file_api_device_v1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_v1_device_proto_goTypes,
		DependencyIndexes: file_api_device_v1_device_proto_depIdxs,
		MessageInfos:      file_api_device_v1_device_proto_msgTypes,
	}.Build()
	File_api_device_v1_device_proto = out.File
	file_api_device_v1_device_proto_goTypes = nil
	file_api_device_v1_device_proto_depIdxs = nil
}
