// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: api/common/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Aud           string                 `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Iat           int64                  `protobuf:"varint,5,opt,name=iat,proto3" json:"iat,omitempty"`
	Iss           string                 `protobuf:"bytes,6,opt,name=iss,proto3" json:"iss,omitempty"`
	Jti           string                 `protobuf:"bytes,7,opt,name=jti,proto3" json:"jti,omitempty"`
	Nbf           int64                  `protobuf:"varint,8,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Sub           string                 `protobuf:"bytes,9,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *TokenClaims) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TokenClaims) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TokenClaims) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *TokenClaims) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *TokenClaims) GetIat() int64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *TokenClaims) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *TokenClaims) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *TokenClaims) GetNbf() int64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *TokenClaims) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

var File_api_common_v1_common_proto protoreflect.FileDescriptor

const file_api_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/common.proto\x12\rapi.common.v1\"\x1f\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xc4\x01\n" +
	"\vTokenClaims\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.api.common.v1.UserR\x04user\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03aud\x18\x03 \x01(\tR\x03aud\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03iat\x18\x05 \x01(\x03R\x03iat\x12\x10\n" +
	"\x03iss\x18\x06 \x01(\tR\x03iss\x12\x10\n" +
	"\x03jti\x18\a \x01(\tR\x03jti\x12\x10\n" +
	"\x03nbf\x18\b \x01(\x03R\x03nbf\x12\x10\n" +
	"\x03sub\x18\t \x01(\tR\x03subB4\n" +
	"\rapi.common.v1P\x01Z!kratos_sample/api/common/v1;v1b\x06proto3"

var (
	file_api_common_v1_common_proto_rawDescOnce sync.Once
	file_api_common_v1_common_proto_rawDescData []byte
)

func file_api_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)))
	})
	return file_api_common_v1_common_proto_rawDescData
}

var file_api_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_common_v1_common_proto_goTypes = []any{
	(*User)(nil),        // 0: api.common.v1.User
	(*TokenClaims)(nil), // 1: api.common.v1.TokenClaims
}
var file_api_common_v1_common_proto_depIdxs = []int32{
	0, // 0: api.common.v1.TokenClaims.user:type_name -> api.common.v1.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_common_v1_common_proto_init() }
func file_api_common_v1_common_proto_init() {
	if File_api_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_common_v1_common_proto_depIdxs,
		MessageInfos:      file_api_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_common_v1_common_proto = out.File
	file_api_common_v1_common_proto_goTypes = nil
	file_api_common_v1_common_proto_depIdxs = nil
}
